<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-VEKRLTS" failures="1" tests="1" name="Test" time="38.456" errors="0" timestamp="18 Feb 2022 05:49:47 GMT">
  <testcase classname="com.selenium.testcases.MyFirstTestCase" name="guestCheckOut" time="10.495">
    <failure type="java.lang.AssertionError" message="expected [Thank you. Your order has been received] but found [Thank you. Your order has been received.]">
      <![CDATA[java.lang.AssertionError: expected [Thank you. Your order has been received] but found [Thank you. Your order has been received.]
	at com.selenium.testcases.MyFirstTestCase.guestCheckOut(MyFirstTestCase.java:41)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- guestCheckOut -->
  <testcase classname="com.selenium.testcases.MyFirstTestCase" name="loginCheckout" time="0.0">
    <ignored/>
  </testcase> <!-- loginCheckout -->
</testsuite> <!-- Test -->
